// Generate Amazon-style alternate "view" crops for real product photos, and
// write a manifest (slug -> [image paths]) consumed by the product gallery.
// Tile/graphic products keep a single image (zoom crops would look bad).
import { createRequire } from "node:module";
import fs from "node:fs";
import path from "node:path";
const require = createRequire("e:/Projects/onlinetech_ug/");
const sharp = require("e:/Projects/onlinetech_ug/node_modules/.pnpm/sharp@0.34.5/node_modules/sharp/lib/index.js");

const ROOT = "e:/Projects/onlinetech_ug";
const DIR = path.join(ROOT, "apps/web/public/products");

// Generated tiles (no real photo) — keep single image.
const TILES = new Set([
  "usb-c-charger-65w", "laptop-charger-pin-90w", "power-bank-20000", "power-bank-10000",
  "ram-ddr4-8gb-sodimm", "ram-ddr4-16gb-sodimm", "ram-ddr4-8gb-dimm",
  "ssd-nvme-500gb", "ssd-480gb-sata", "sandisk-flash-64gb", "kingston-flash-32gb", "microsd-64gb",
  "laptop-backpack-grey", "lenovo-thinkbook-backpack",
]);

const bases = fs
  .readdirSync(DIR)
  .filter((f) => f.endsWith(".webp") && !/-[23]\.webp$/.test(f))
  .map((f) => f.replace(".webp", ""));

const manifest = {};

for (const slug of bases) {
  const src = path.join(DIR, `${slug}.webp`);
  const imgs = [`/products/${slug}.webp`];

  if (!TILES.has(slug)) {
    // -2: medium center zoom; -3: closer zoom — alternate "detail" views.
    const meta = await sharp(src).metadata();
    const W = meta.width ?? 900;
    const H = meta.height ?? 900;
    const make = async (factor, suffix, yBias) => {
      const w = Math.round(W / factor);
      const h = Math.round(H / factor);
      const left = Math.round((W - w) / 2);
      const top = Math.max(0, Math.round((H - h) / 2 - yBias));
      await sharp(src)
        .extract({ left, top, width: w, height: Math.min(h, H - top) })
        .resize(900, 900, { fit: "contain", background: "#ffffff" })
        .flatten({ background: "#ffffff" })
        .webp({ quality: 82 })
        .toFile(path.join(DIR, `${slug}-${suffix}.webp`));
      imgs.push(`/products/${slug}-${suffix}.webp`);
    };
    try {
      await make(1.45, "2", Math.round(H * 0.08));
      await make(1.9, "3", 0);
    } catch (e) {
      console.warn("crop fail", slug, e.message);
    }
  }

  manifest[slug] = imgs;
}

const ts =
  "// Auto-generated by scripts/product-views.mjs — product image gallery sources.\n" +
  "export const productImages: Record<string, string[]> = " +
  JSON.stringify(manifest, null, 2) +
  ";\n";
fs.writeFileSync(path.join(ROOT, "apps/web/src/lib/product-images.ts"), ts);
console.log("products with galleries:", Object.values(manifest).filter((a) => a.length > 1).length, "/ total", bases.length);
