"""Regenerate the storefront's note previews from the server's note bodies.

The full notes are premium and live on the server; the site only needs each
unit's number, title and summary so it can list them behind the lock. Keeping
the two in step by hand meant a course could have notes nobody could see, so
this derives one from the other.

    python scripts/build_course_note_previews.py

Writes apps/web/src/lib/course-notes.ts.
"""

from __future__ import annotations

import json
import pathlib

API_ROOT = pathlib.Path(__file__).resolve().parents[1]
NOTES_JSON = API_ROOT / "app" / "data" / "course_notes.json"
OUT_TS = API_ROOT.parents[0] / "web" / "src" / "lib" / "course-notes.ts"

HEADER = """// Titles/summaries only — the full note content lives on the SERVER and is
// fetched (gated) from /api/v1/courses/{slug}/notes. This keeps premium content
// out of the browser bundle. See apps/api/app/api/routes/courses.py.
//
// Generated by apps/api/scripts/build_course_note_previews.py — do not edit by
// hand; edit app/data/course_notes.json and run the script again.

export type NoteMeta = { n: number; title: string; summary: string };

export const courseNotes: Record<string, NoteMeta[]> = """


def main() -> None:
    data = json.loads(NOTES_JSON.read_text(encoding="utf-8"))

    previews = {
        slug: [
            {
                "n": unit.get("n", i + 1),
                "title": unit.get("title", ""),
                "summary": unit.get("summary", ""),
            }
            for i, unit in enumerate(units)
        ]
        for slug, units in data.items()
    }

    body = json.dumps(previews, indent=2, ensure_ascii=False)
    OUT_TS.write_text(HEADER + body + ";\n", encoding="utf-8", newline="\n")

    units = sum(len(v) for v in previews.values())
    print(f"wrote {OUT_TS.relative_to(API_ROOT.parents[1])}")
    print(f"  {len(previews)} courses, {units} units")


if __name__ == "__main__":
    main()
