// Weekly tech blog articles. Add a new entry at the top each week.
export type Block = { h?: string; p?: string };

export type Article = {
  slug: string;
  title: string;
  excerpt: string;
  category: "Buying Guides" | "Tips" | "Business" | "Security";
  author: string;
  date: string; // ISO
  readMins: number;
  image: string; // headline image
  body: Block[];
};

export const articles: Article[] = [
  {
    slug: "ssd-vs-hdd-upgrade",
    title: "SSD vs HDD: The Upgrade That Transforms Your PC",
    excerpt: "Swapping an old hard drive for an SSD is the single best speed upgrade you can make — here's why.",
    category: "Tips",
    author: "Online Tech Uganda",
    date: "2026-08-22T09:00:00+03:00",
    readMins: 4,
    image: "https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=1000&q=70",
    body: [
      { p: "If your computer takes minutes to start and freezes when you open a few programs, the problem is usually the hard drive — not the whole machine." },
      { h: "What's the difference?" },
      { p: "An HDD (hard disk drive) uses spinning platters and is slow. An SSD (solid state drive) has no moving parts and reads data many times faster, so Windows boots in seconds and apps open instantly." },
      { h: "The numbers" },
      { p: "A typical HDD reads at about 100MB/s. A SATA SSD does around 500MB/s, and an NVMe SSD can exceed 3,500MB/s. That's why an SSD feels like a brand-new computer." },
      { h: "Do I need a new laptop?" },
      { p: "Often no. If your machine still has an HDD, adding a 256GB–1TB SSD (and maybe more RAM) brings it back to life for a fraction of the cost of a new one." },
      { p: "We stock genuine SSDs from 240GB to 2TB and can install and clone your data the same day. Chat with us on WhatsApp for a quote." },
    ],
  },
  {
    slug: "speed-up-a-slow-laptop",
    title: "7 Ways to Speed Up a Slow Laptop (No New Hardware Needed)",
    excerpt: "Before you buy a new machine, try these free fixes that make a slow laptop noticeably faster.",
    category: "Tips",
    author: "Agaba Geofrey",
    date: "2026-08-18T09:00:00+03:00",
    readMins: 5,
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1000&q=70",
    body: [
      { p: "A slow laptop is frustrating, but you can often fix it in minutes without spending money." },
      { h: "1. Close startup programs" },
      { p: "Many apps launch with Windows and eat resources. Open Task Manager → Startup and disable what you don't need." },
      { h: "2. Free up disk space" },
      { p: "A full drive slows everything down. Delete old downloads, empty the recycle bin, and uninstall programs you never use." },
      { h: "3. Scan for malware" },
      { p: "Viruses and unwanted software silently use your CPU. Run a full scan with Windows Defender or a trusted antivirus." },
      { h: "4. Update Windows & drivers" },
      { p: "Updates fix bugs and improve performance. Keep Windows and your graphics/chipset drivers current." },
      { h: "5. Reduce visual effects" },
      { p: "Turn off animations under Performance Options for an instant snappier feel on older machines." },
      { h: "6. Upgrade RAM or add an SSD" },
      { p: "If it's still slow, 8GB→16GB RAM and an SSD make the biggest difference. This is a cheap upgrade we can do for you." },
      { h: "7. Reset as a last resort" },
      { p: "A clean Windows reinstall clears years of clutter. Back up your files first — or let us handle it safely." },
    ],
  },
  {
    slug: "best-laptops-for-students-uganda",
    title: "Best Laptops for Students in Uganda (2026)",
    excerpt: "Reliable, affordable laptops that handle research, assignments and online classes without breaking the bank.",
    category: "Buying Guides",
    author: "Online Tech Uganda",
    date: "2026-08-12T09:00:00+03:00",
    readMins: 5,
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1000&q=70",
    body: [
      { p: "Students need a laptop that's affordable, portable and tough enough for daily campus life. Here's what to look for and our top picks." },
      { h: "What specs do students really need?" },
      { p: "For most courses: an Intel Core i5 (or Ryzen 5), 8GB RAM, and a 256GB SSD is the sweet spot. It runs Office, Zoom, browsers and research tools smoothly." },
      { h: "Best value: UK-used business laptops" },
      { p: "HP EliteBook, Dell Latitude and Lenovo ThinkPad give premium build quality and long battery life for less. They survive the daily commute better than cheap plastic laptops." },
      { h: "For design & engineering students" },
      { p: "If you use AutoCAD, Photoshop or coding IDEs, step up to Core i7, 16GB RAM and a dedicated GPU." },
      { h: "Don't forget the extras" },
      { p: "A laptop bag, a mouse and a power bank make campus life easier. Ask us about our student bundles." },
    ],
  },
  {
    slug: "protect-your-laptop-from-viruses",
    title: "How to Protect Your Laptop from Viruses & Malware",
    excerpt: "Simple habits that keep your files, passwords and money safe from the most common threats.",
    category: "Security",
    author: "Online Tech Uganda",
    date: "2026-08-06T09:00:00+03:00",
    readMins: 4,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1000&q=70",
    body: [
      { p: "Most infections come from a few avoidable mistakes. Follow these to stay safe." },
      { h: "Use genuine antivirus" },
      { p: "Windows Defender is good and free. Keep it turned on and let it update automatically." },
      { h: "Be careful with downloads & flash drives" },
      { p: "Only download software from official sites, and scan every flash drive before opening it — USB drives are a top way viruses spread in Uganda." },
      { h: "Don't click suspicious links" },
      { p: "Fake 'you've won' messages and login pages steal your accounts. When in doubt, don't click." },
      { h: "Back up your important files" },
      { p: "If ransomware ever locks your PC, a backup means you lose nothing. Use an external drive or cloud storage." },
      { p: "We offer virus removal and data recovery — bring your machine in or chat with us on WhatsApp." },
    ],
  },
  {
    slug: "small-business-data-backup",
    title: "Why Every Small Business Needs a Data Backup Plan",
    excerpt: "Losing your customer records or accounts overnight can cripple a business. Here's how to protect your data.",
    category: "Business",
    author: "Agaba Geofrey",
    date: "2026-07-30T09:00:00+03:00",
    readMins: 4,
    image: "https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=1000&q=70",
    body: [
      { p: "Hard drives fail, laptops get stolen, and ransomware happens. For a business, lost data can mean lost customers and money." },
      { h: "The 3-2-1 rule" },
      { p: "Keep 3 copies of your data, on 2 different types of storage, with 1 copy off-site (like the cloud). It's the gold standard used worldwide." },
      { h: "Easy options for small businesses" },
      { p: "An external hard drive for local backups plus Google Drive or OneDrive for off-site copies covers most shops and offices affordably." },
      { h: "Automate it" },
      { p: "Backups only work if they actually happen. Set them to run automatically so you never have to remember." },
      { p: "We help businesses set up reliable, automatic backups and supply external drives and NAS storage. Talk to us." },
    ],
  },
  {
    slug: "gaming-laptop-specs-that-matter",
    title: "Gaming Laptops: What Specs Actually Matter",
    excerpt: "GPU, refresh rate, cooling — cut through the jargon and buy the right gaming laptop for your budget.",
    category: "Buying Guides",
    author: "Online Tech Uganda",
    date: "2026-07-24T09:00:00+03:00",
    readMins: 5,
    image: "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=1000&q=70",
    body: [
      { p: "Gaming laptops range widely in price. Knowing which specs matter helps you spend where it counts." },
      { h: "The GPU is king" },
      { p: "The graphics card decides your gaming performance. An NVIDIA RTX 3050/4050 handles most games at 1080p; RTX 4060 and up gives higher settings and frame rates." },
      { h: "CPU & RAM" },
      { p: "A Core i5/i7 or Ryzen 5/7 with 16GB RAM keeps games and background apps smooth. 8GB is not enough for modern gaming." },
      { h: "Refresh rate & display" },
      { p: "A 144Hz screen makes fast games feel much smoother than a standard 60Hz panel — a big deal for competitive titles." },
      { h: "Cooling matters" },
      { p: "Good cooling keeps performance high during long sessions. Brands like HP OMEN/Victus and Lenovo Legion are built for it." },
      { p: "We stock gaming laptops from HP OMEN, Victus and Lenovo Legion. Tell us your budget and games, and we'll match you." },
    ],
  },
  {
    slug: "how-to-choose-a-laptop-in-uganda",
    title: "How to Choose the Right Laptop in Uganda (2026)",
    excerpt: "RAM, storage, processor and budget — a simple guide to picking a laptop that fits your needs.",
    category: "Buying Guides",
    author: "Agaba Geofrey",
    date: "2026-06-22T09:00:00+03:00",
    readMins: 5,
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1000&q=70",
    body: [
      { p: "Buying a laptop can feel confusing with all the specs. Here's how to keep it simple and get value for your money." },
      { h: "1. Start with what you'll do" },
      { p: "For browsing, typing and online classes, a Core i3/i5 with 8GB RAM and an SSD is plenty. For design, editing or gaming, look at Core i7/Ryzen 7 with 16GB RAM and a dedicated graphics card (like RTX 3060)." },
      { h: "2. SSD over HDD — always" },
      { p: "An SSD makes a laptop feel several times faster than an old hard drive. If a machine still has an HDD, budget for an SSD upgrade — it's the best value upgrade you can make." },
      { h: "3. RAM: 8GB minimum" },
      { p: "8GB handles everyday work. 16GB is better if you keep many browser tabs open or run heavier software. Most business laptops can be upgraded later." },
      { h: "4. UK Used vs Brand New" },
      { p: "UK-Used business laptops (HP EliteBook, Dell Latitude, Lenovo ThinkPad) offer premium build at lower prices. Brand new gives you warranty and the latest specs. We quality-check every UK-used machine before sale." },
      { p: "Need help deciding? Chat with us on WhatsApp and we'll recommend the best option for your budget." },
    ],
  },
  {
    slug: "uk-used-vs-brand-new-laptops",
    title: "UK Used vs Brand New Laptops — Which Should You Buy?",
    excerpt: "Both are great choices. Here's how to decide based on budget, warranty and how you'll use it.",
    category: "Buying Guides",
    author: "Online Tech Uganda",
    date: "2026-06-15T09:00:00+03:00",
    readMins: 4,
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1000&q=70",
    body: [
      { p: "One of the most common questions we get: should I buy UK-used or brand new? The honest answer — it depends." },
      { h: "Why UK-Used is popular" },
      { p: "UK-used business laptops are built tougher than many new budget laptops. You get premium metal bodies, great keyboards and strong performance for much less money." },
      { h: "When to buy Brand New" },
      { p: "Choose brand new when you want a manufacturer warranty, the newest processors, or a specific model like a gaming laptop or MacBook." },
      { h: "Our promise" },
      { p: "Every UK-used device we sell is tested for battery health, screen, keyboard, ports and performance — so you buy with confidence." },
    ],
  },
  {
    slug: "protect-yourself-from-online-scams",
    title: "5 Ways to Protect Yourself From Online & Mobile Money Scams",
    excerpt: "Simple habits that keep your money and accounts safe online.",
    category: "Security",
    author: "Online Tech Uganda",
    date: "2026-06-08T09:00:00+03:00",
    readMins: 4,
    image: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=1000&q=70",
    body: [
      { p: "Scammers are getting smarter. These five habits will keep you safe." },
      { h: "1. Never share your PIN or OTP" },
      { p: "No real bank, telecom or company will ever ask for your Mobile Money PIN or a one-time code. Anyone who does is a scammer." },
      { h: "2. Confirm the number before sending money" },
      { p: "Double-check the name and number before approving any Mobile Money transaction." },
      { h: "3. Use strong, unique passwords" },
      { p: "Long passwords with a mix of letters and numbers — and don't reuse the same one everywhere." },
      { h: "4. Be careful with links" },
      { p: "If a message says you've won money you never entered for, it's a scam. Don't click." },
      { h: "5. Keep software updated" },
      { p: "Updates fix security holes. Turn on automatic updates for your phone and computer." },
    ],
  },
  {
    slug: "why-your-business-needs-a-website",
    title: "Why Every Ugandan Business Needs a Website in 2026",
    excerpt: "A website works for you 24/7 — building trust and bringing in customers.",
    category: "Business",
    author: "Agaba Geofrey",
    date: "2026-06-01T09:00:00+03:00",
    readMins: 4,
    image: "https://images.unsplash.com/photo-1547658719-da2b51169166?auto=format&fit=crop&w=1000&q=70",
    body: [
      { p: "Social media is great, but a website is your business's home online — one you fully own and control." },
      { h: "It builds trust" },
      { p: "Customers check you online before buying. A clean, professional website signals that you're a real, serious business." },
      { h: "It sells while you sleep" },
      { p: "With an online store or enquiry form, customers can buy or reach you any time — not only when you're online." },
      { h: "It's more affordable than you think" },
      { p: "We build fast, mobile-friendly websites for Ugandan businesses from UGX 500,000. Request a quote and we'll propose a plan." },
    ],
  },
];

export function findArticle(slug: string) {
  return articles.find((a) => a.slug === slug);
}
