// Catalog seed data. Slugs (id) are kept in sync with apps/api/app/services/catalog.py
// so checkout price-validation matches. Computers span budget → high-end (UGX 550k+).

export type ProductDetails = {
  type: string; // e.g. Business Ultrabook, Gaming Laptop, Desktop Tower
  processor: string; // full CPU incl. i-Core / Ryzen model
  generation: string; // e.g. 11th Gen, Apple M1
  ram: string; // size + type
  storage: string; // size + type (SSD/HDD)
  graphics: string; // integrated or dedicated GPU
  display: string; // size + resolution
  os: string; // Windows / macOS
  battery: string; // battery life
  ports: string; // ports & connectivity
  build: string; // build quality
  purpose: string; // what the machine is best for
};

export type Product = {
  id: string;
  name: string;
  category: "Laptops" | "Desktops" | "Components" | "Power" | "Accessories" | "Networking" | "Storage";
  price: number; // UGX
  oldPrice?: number;
  brand: string;
  condition: "Brand New" | "UK Used" | "Refurbished";
  rating: number;
  badge?: string;
  inStock?: boolean; // defaults to true when omitted
  image?: string; // remote/web image URL; falls back to /products/<id>.webp
  specs: string[]; // short bullets for cards/grid
  details?: ProductDetails; // full specification (computers)
};

// Resolve a product's image: an explicit web URL if provided, else the local
// curated photo by slug convention.
export function productImage(p: Pick<Product, "id" | "image">): string {
  return p.image ?? `/products/${p.id}.webp`;
}

export const products: Product[] = [
  // ── Budget laptops (550k – 1M) ──────────────────────────────
  {
    id: "dell-latitude-e6440",
    name: "Dell Latitude E6440",
    category: "Laptops",
    price: 650000,
    brand: "Dell",
    condition: "UK Used",
    rating: 4.3,
    badge: "Budget pick",
    specs: ["Core i5 4th Gen", "4GB RAM", "320GB HDD", '14" HD', "Windows 10"],
    details: {
      type: "Business Laptop",
      processor: "Intel Core i5-4300U",
      generation: "4th Generation",
      ram: "4GB DDR3 (upgradable to 16GB)",
      storage: "320GB HDD",
      graphics: "Intel HD Graphics 4400 (integrated)",
      display: '14" HD (1366 × 768)',
      os: "Windows 10 Pro",
      battery: "Up to 4 hours",
      ports: "USB 3.0, HDMI, VGA, Ethernet (RJ-45), SD card reader",
      build: "Durable business-grade chassis",
      purpose: "Everyday office work, browsing and students on a tight budget",
    },
  },
  {
    id: "hp-elitebook-840-g1",
    name: "HP EliteBook 840 G1",
    category: "Laptops",
    price: 700000,
    brand: "HP",
    condition: "UK Used",
    rating: 4.3,
    specs: ["Core i5 4th Gen", "4GB RAM", "500GB HDD", '14" HD', "Windows 10"],
    details: {
      type: "Business Laptop",
      processor: "Intel Core i5-4300U",
      generation: "4th Generation",
      ram: "4GB DDR3 (upgradable to 16GB)",
      storage: "500GB HDD",
      graphics: "Intel HD Graphics 4400 (integrated)",
      display: '14" HD (1366 × 768)',
      os: "Windows 10 Pro",
      battery: "Up to 5 hours",
      ports: "USB 3.0, DisplayPort, VGA, Ethernet (RJ-45)",
      build: "Premium aluminium-magnesium body",
      purpose: "Reliable, affordable business laptop for office and study",
    },
  },
  {
    id: "lenovo-thinkpad-x240",
    name: "Lenovo ThinkPad X240",
    category: "Laptops",
    price: 780000,
    brand: "Lenovo",
    condition: "UK Used",
    rating: 4.4,
    inStock: false,
    specs: ["Core i5 4th Gen", "8GB RAM", "128GB SSD", '12.5" HD', "Lightweight"],
    details: {
      type: "Ultraportable Business Laptop",
      processor: "Intel Core i5-4300U",
      generation: "4th Generation",
      ram: "8GB DDR3",
      storage: "128GB SSD",
      graphics: "Intel HD Graphics 4400 (integrated)",
      display: '12.5" HD (1366 × 768)',
      os: "Windows 10 Pro",
      battery: "Up to 7 hours (dual battery)",
      ports: "USB 3.0, Mini DisplayPort, Ethernet (RJ-45)",
      build: "Legendary ThinkPad durability, MIL-SPEC tested",
      purpose: "Highly portable laptop for travel, meetings and note-taking",
    },
  },
  {
    id: "hp-probook-640-g2",
    name: "HP ProBook 640 G2",
    category: "Laptops",
    price: 880000,
    brand: "HP",
    condition: "UK Used",
    rating: 4.4,
    specs: ["Core i5 6th Gen", "8GB RAM", "256GB SSD", '14" HD'],
    details: {
      type: "Business Laptop",
      processor: "Intel Core i5-6200U",
      generation: "6th Generation",
      ram: "8GB DDR4",
      storage: "256GB SSD",
      graphics: "Intel HD Graphics 520 (integrated)",
      display: '14" HD (1366 × 768)',
      os: "Windows 10 Pro",
      battery: "Up to 6 hours",
      ports: "USB 3.0, USB-C, HDMI, VGA, Ethernet (RJ-45)",
      build: "Sturdy business chassis",
      purpose: "Faster everyday productivity with quick SSD storage",
    },
  },
  {
    id: "dell-latitude-e7270",
    name: "Dell Latitude E7270",
    category: "Laptops",
    price: 980000,
    brand: "Dell",
    condition: "UK Used",
    rating: 4.5,
    specs: ["Core i5 6th Gen", "8GB RAM", "256GB SSD", '12.5" FHD', "Ultrabook"],
    details: {
      type: "Ultrabook",
      processor: "Intel Core i5-6300U",
      generation: "6th Generation",
      ram: "8GB DDR4",
      storage: "256GB SSD",
      graphics: "Intel HD Graphics 520 (integrated)",
      display: '12.5" Full HD (1920 × 1080)',
      os: "Windows 10 Pro",
      battery: "Up to 7 hours",
      ports: "USB 3.0, USB-C, HDMI, Mini DisplayPort",
      build: "Premium, lightweight ultrabook design",
      purpose: "Slim, light laptop for professionals on the move",
    },
  },

  // ── Mid-range laptops (1M – 2M) ─────────────────────────────
  {
    id: "hp-elitebook-840-g3",
    name: "HP EliteBook 840 G3",
    category: "Laptops",
    price: 1250000,
    brand: "HP",
    condition: "UK Used",
    rating: 4.5,
    specs: ["Core i5 6th Gen", "8GB RAM", "256GB SSD", '14" FHD'],
    details: {
      type: "Business Ultrabook",
      processor: "Intel Core i5-6300U",
      generation: "6th Generation",
      ram: "8GB DDR4 (upgradable to 32GB)",
      storage: "256GB SSD",
      graphics: "Intel HD Graphics 520 (integrated)",
      display: '14" Full HD (1920 × 1080)',
      os: "Windows 10 Pro",
      battery: "Up to 8 hours",
      ports: "USB 3.0, USB-C, DisplayPort, VGA, Ethernet (RJ-45)",
      build: "Premium aluminium, MIL-STD 810G tested",
      purpose: "Professional work, multitasking and presentations",
    },
  },
  {
    id: "lenovo-thinkpad-t460",
    name: "Lenovo ThinkPad T460",
    category: "Laptops",
    price: 1350000,
    brand: "Lenovo",
    condition: "UK Used",
    rating: 4.6,
    specs: ["Core i5 6th Gen", "8GB RAM", "256GB SSD", '14" FHD', "Dual battery"],
    details: {
      type: "Business Laptop",
      processor: "Intel Core i5-6300U",
      generation: "6th Generation",
      ram: "8GB DDR4 (upgradable to 32GB)",
      storage: "256GB SSD",
      graphics: "Intel HD Graphics 520 (integrated)",
      display: '14" Full HD (1920 × 1080)',
      os: "Windows 10 Pro",
      battery: "Up to 10 hours (dual battery)",
      ports: "USB 3.0, USB-C, HDMI, Mini DisplayPort, Ethernet (RJ-45)",
      build: "ThinkPad MIL-SPEC durability",
      purpose: "All-day business computing with extra-long battery life",
    },
  },
  {
    id: "dell-latitude-7390",
    name: "Dell Latitude 7390",
    category: "Laptops",
    price: 1650000,
    brand: "Dell",
    condition: "UK Used",
    rating: 4.6,
    specs: ["Core i5 8th Gen", "8GB RAM", "256GB SSD", '13.3" FHD'],
    details: {
      type: "Business Ultrabook",
      processor: "Intel Core i5-8350U",
      generation: "8th Generation",
      ram: "8GB DDR4 (upgradable to 16GB)",
      storage: "256GB NVMe SSD",
      graphics: "Intel UHD Graphics 620 (integrated)",
      display: '13.3" Full HD (1920 × 1080)',
      os: "Windows 11 Pro",
      battery: "Up to 9 hours",
      ports: "USB-C Thunderbolt, USB 3.1, HDMI, microSD",
      build: "Compact carbon-fibre, durable",
      purpose: "Modern, fast laptop for professionals and students",
    },
  },
  {
    id: "lenovo-thinkpad-t14",
    name: "Lenovo ThinkPad T14",
    category: "Laptops",
    price: 1980000,
    brand: "Lenovo",
    condition: "UK Used",
    rating: 4.5,
    specs: ["Core i5 10th Gen", "8GB RAM", "256GB SSD", '14" HD'],
    details: {
      type: "Business Laptop",
      processor: "Intel Core i5-10210U",
      generation: "10th Generation",
      ram: "8GB DDR4 (upgradable to 32GB)",
      storage: "256GB NVMe SSD",
      graphics: "Intel UHD Graphics (integrated)",
      display: '14" HD (1366 × 768)',
      os: "Windows 11 Pro",
      battery: "Up to 10 hours",
      ports: "USB-C, USB 3.2, HDMI, Ethernet (RJ-45)",
      build: "Robust ThinkPad, MIL-SPEC tested",
      purpose: "Dependable workhorse for business and coding",
    },
  },

  // ── Premium laptops (2M – 4M) ───────────────────────────────
  {
    id: "hp-elitebook-840-g8",
    name: "HP EliteBook 840 G8",
    category: "Laptops",
    price: 2450000,
    brand: "HP",
    condition: "UK Used",
    rating: 4.7,
    badge: "Best seller",
    specs: ["Core i5 11th Gen", "16GB RAM", "512GB SSD", '14" FHD'],
    details: {
      type: "Business Ultrabook",
      processor: "Intel Core i5-1135G7",
      generation: "11th Generation",
      ram: "16GB DDR4",
      storage: "512GB NVMe SSD",
      graphics: "Intel Iris Xe (integrated)",
      display: '14" Full HD (1920 × 1080)',
      os: "Windows 11 Pro",
      battery: "Up to 11 hours",
      ports: "2× USB-C Thunderbolt 4, 2× USB-A, HDMI",
      build: "Premium aluminium, MIL-STD 810H tested",
      purpose: "Powerful everyday performance for professionals and multitasking",
    },
  },
  {
    id: "dell-latitude-7420",
    name: "Dell Latitude 7420",
    category: "Laptops",
    price: 2380000,
    brand: "Dell",
    condition: "UK Used",
    rating: 4.6,
    specs: ["Core i7 11th Gen", "16GB RAM", "256GB SSD", '14" FHD'],
    details: {
      type: "Business Ultrabook",
      processor: "Intel Core i7-1165G7",
      generation: "11th Generation",
      ram: "16GB DDR4",
      storage: "256GB NVMe SSD",
      graphics: "Intel Iris Xe (integrated)",
      display: '14" Full HD (1920 × 1080)',
      os: "Windows 11 Pro",
      battery: "Up to 12 hours",
      ports: "USB-C Thunderbolt 4, USB-A, HDMI, microSD",
      build: "Premium carbon-fibre / aluminium",
      purpose: "High performance for demanding office workloads",
    },
  },
  {
    id: "dell-xps-13-9310",
    name: "Dell XPS 13 9310",
    category: "Laptops",
    price: 3650000,
    brand: "Dell",
    condition: "Refurbished",
    rating: 4.8,
    badge: "Premium",
    specs: ["Core i7 11th Gen", "16GB RAM", "512GB SSD", '13.4" FHD+ touch'],
    details: {
      type: "Premium Ultrabook",
      processor: "Intel Core i7-1185G7",
      generation: "11th Generation",
      ram: "16GB LPDDR4x",
      storage: "512GB NVMe SSD",
      graphics: "Intel Iris Xe (integrated)",
      display: '13.4" FHD+ (1920 × 1200) touchscreen',
      os: "Windows 11 Home",
      battery: "Up to 12 hours",
      ports: "2× USB-C Thunderbolt 4, microSD",
      build: "CNC machined aluminium + carbon fibre",
      purpose: "Sleek premium laptop for professionals and creators",
    },
  },
  {
    id: "macbook-air-m1",
    name: "Apple MacBook Air M1",
    category: "Laptops",
    price: 3990000,
    brand: "Apple",
    condition: "Refurbished",
    rating: 4.9,
    badge: "Top rated",
    specs: ["Apple M1", "8GB RAM", "256GB SSD", '13.3" Retina'],
    details: {
      type: "Ultrabook",
      processor: "Apple M1 (8-core CPU)",
      generation: "Apple M1",
      ram: "8GB unified memory",
      storage: "256GB SSD",
      graphics: "7-core Apple GPU",
      display: '13.3" Retina (2560 × 1600)',
      os: "macOS",
      battery: "Up to 18 hours",
      ports: "2× Thunderbolt / USB 4, 3.5mm audio",
      build: "Aluminium unibody, fanless (silent)",
      purpose: "Long-battery, silent powerhouse for students and creatives",
    },
  },
  {
    id: "hp-spectre-x360-14",
    name: "HP Spectre x360 14",
    category: "Laptops",
    price: 3900000,
    brand: "HP",
    condition: "Refurbished",
    rating: 4.7,
    specs: ["Core i7 11th Gen", "16GB RAM", "512GB SSD", '13.5" OLED touch', "2-in-1"],
    details: {
      type: "2-in-1 Convertible Laptop",
      processor: "Intel Core i7-1165G7",
      generation: "11th Generation",
      ram: "16GB LPDDR4x",
      storage: "512GB NVMe SSD",
      graphics: "Intel Iris Xe (integrated)",
      display: '13.5" OLED (3000 × 2000) touchscreen',
      os: "Windows 11 Home",
      battery: "Up to 16 hours",
      ports: "2× Thunderbolt 4, USB-A, microSD",
      build: "Gem-cut aluminium, premium convertible",
      purpose: "Premium flip laptop for creativity and entertainment",
    },
  },

  {
    id: "hp-pavilion-x360-13",
    name: "HP Pavilion x360 13",
    category: "Laptops",
    price: 2250000,
    brand: "HP",
    condition: "UK Used",
    rating: 4.6,
    badge: "2-in-1",
    specs: ["Core i5 11th Gen", "8GB RAM", "256GB SSD", '13.3" FHD touch', "Convertible"],
    details: {
      type: "2-in-1 Convertible Laptop",
      processor: "Intel Core i5-1135G7",
      generation: "11th Generation",
      ram: "8GB DDR4 (upgradable to 16GB)",
      storage: "256GB NVMe SSD",
      graphics: "Intel Iris Xe (integrated)",
      display: '13.3" Full HD (1920 × 1080) touchscreen',
      os: "Windows 11 Home",
      battery: "Up to 10 hours",
      ports: "USB-C, 2× USB-A, HDMI, microSD, fingerprint reader",
      build: "Slim silver aluminium, 360° flip hinge",
      purpose: "Flexible 2-in-1 for study, work and entertainment — use as laptop or tablet",
    },
  },

  // ── High-end & gaming (4M+) ─────────────────────────────────
  {
    id: "lenovo-legion-5-15",
    name: "Lenovo Legion 5 (RTX 3060)",
    category: "Laptops",
    price: 4990000,
    brand: "Lenovo",
    condition: "Brand New",
    rating: 4.7,
    badge: "Gaming",
    specs: ["Ryzen 7", "16GB RAM", "512GB SSD", "RTX 3060 6GB", '15.6" 165Hz'],
    details: {
      type: "Gaming Laptop",
      processor: "AMD Ryzen 7 5800H (8-core)",
      generation: "Ryzen 5000 Series",
      ram: "16GB DDR4",
      storage: "512GB NVMe SSD",
      graphics: "NVIDIA GeForce RTX 3060 6GB (dedicated)",
      display: '15.6" Full HD (1920 × 1080) 165Hz',
      os: "Windows 11 Home",
      battery: "Up to 6 hours",
      ports: "USB-C, 3× USB-A, HDMI, Ethernet (RJ-45)",
      build: "Gaming chassis with advanced cooling",
      purpose: "Smooth gaming, video editing and 3D rendering",
    },
  },
  {
    id: "asus-rog-strix-g15",
    name: "ASUS ROG Strix G15",
    category: "Laptops",
    price: 5300000,
    brand: "ASUS",
    condition: "Brand New",
    rating: 4.7,
    badge: "Gaming",
    specs: ["Ryzen 7", "16GB RAM", "1TB SSD", "RTX 3060 6GB", '15.6" 144Hz'],
    details: {
      type: "Gaming Laptop",
      processor: "AMD Ryzen 7 5800H (8-core)",
      generation: "Ryzen 5000 Series",
      ram: "16GB DDR4",
      storage: "1TB NVMe SSD",
      graphics: "NVIDIA GeForce RTX 3060 6GB (dedicated)",
      display: '15.6" Full HD (1920 × 1080) 144Hz',
      os: "Windows 11 Home",
      battery: "Up to 6 hours",
      ports: "USB-C, USB-A, HDMI, Ethernet (RJ-45)",
      build: "ROG gaming build with RGB and intelligent cooling",
      purpose: "High-FPS gaming and heavy creative workloads",
    },
  },
  {
    id: "dell-xps-15-9520",
    name: "Dell XPS 15 9520",
    category: "Laptops",
    price: 5200000,
    brand: "Dell",
    condition: "Refurbished",
    rating: 4.8,
    specs: ["Core i7 12th Gen", "16GB RAM", "512GB SSD", '15.6" OLED', "RTX graphics"],
    details: {
      type: "Creator Laptop",
      processor: "Intel Core i7-12700H (14-core)",
      generation: "12th Generation",
      ram: "16GB DDR5",
      storage: "512GB NVMe SSD",
      graphics: "NVIDIA GeForce RTX 3050 4GB (dedicated)",
      display: '15.6" 3.5K OLED (3456 × 2160) touchscreen',
      os: "Windows 11 Pro",
      battery: "Up to 10 hours",
      ports: "2× Thunderbolt 4, USB-C, SD card reader",
      build: "CNC aluminium + carbon fibre, premium",
      purpose: "Professional content creation, design and editing",
    },
  },
  {
    id: "macbook-pro-14-m3",
    name: 'Apple MacBook Pro 14" M3',
    category: "Laptops",
    price: 7200000,
    brand: "Apple",
    condition: "Brand New",
    rating: 4.9,
    badge: "Flagship",
    specs: ["Apple M3", "16GB RAM", "512GB SSD", '14.2" Liquid Retina XDR'],
    details: {
      type: "Professional Laptop",
      processor: "Apple M3 (8-core CPU)",
      generation: "Apple M3",
      ram: "16GB unified memory",
      storage: "512GB SSD",
      graphics: "10-core Apple GPU",
      display: '14.2" Liquid Retina XDR (3024 × 1964)',
      os: "macOS",
      battery: "Up to 18 hours",
      ports: "3× Thunderbolt 4, HDMI, SDXC, MagSafe 3",
      build: "Aluminium unibody, premium pro build",
      purpose: "Demanding creative and development work at pro performance",
    },
  },

  {
    id: "macbook-air-m2",
    name: "Apple MacBook Air M2",
    category: "Laptops",
    price: 4600000,
    brand: "Apple",
    condition: "Refurbished",
    rating: 4.9,
    badge: "Top rated",
    specs: ["Apple M2", "8GB RAM", "256GB SSD", '13.6" Liquid Retina'],
    details: {
      type: "Ultrabook",
      processor: "Apple M2 (8-core CPU)",
      generation: "Apple M2",
      ram: "8GB unified memory",
      storage: "256GB SSD",
      graphics: "10-core Apple GPU",
      display: '13.6" Liquid Retina (2560 × 1664)',
      os: "macOS",
      battery: "Up to 18 hours",
      ports: "2× Thunderbolt / USB 4, MagSafe, 3.5mm",
      build: "Aluminium unibody, fanless (silent)",
      purpose: "Slim, silent, long-battery laptop for students and creatives",
    },
  },
  {
    id: "macbook-pro-13-m2",
    name: 'Apple MacBook Pro 13" M2',
    category: "Laptops",
    price: 5500000,
    brand: "Apple",
    condition: "Refurbished",
    rating: 4.8,
    specs: ["Apple M2", "8GB RAM", "256GB SSD", '13.3" Retina'],
    details: {
      type: "Professional Laptop",
      processor: "Apple M2 (8-core CPU)",
      generation: "Apple M2",
      ram: "8GB unified memory",
      storage: "256GB SSD",
      graphics: "10-core Apple GPU",
      display: '13.3" Retina (2560 × 1600)',
      os: "macOS",
      battery: "Up to 20 hours",
      ports: "2× Thunderbolt / USB 4, 3.5mm",
      build: "Aluminium unibody with active cooling",
      purpose: "Pro performance with all-day battery for creators and developers",
    },
  },
  {
    id: "asus-vivobook-15",
    name: "ASUS VivoBook 15",
    category: "Laptops",
    price: 1850000,
    brand: "ASUS",
    condition: "Brand New",
    rating: 4.5,
    badge: "New",
    specs: ["Core i5 11th Gen", "8GB RAM", "512GB SSD", '15.6" FHD'],
    details: {
      type: "Everyday Laptop",
      processor: "Intel Core i5-1135G7",
      generation: "11th Generation",
      ram: "8GB DDR4 (upgradable)",
      storage: "512GB NVMe SSD",
      graphics: "Intel Iris Xe (integrated)",
      display: '15.6" Full HD (1920 × 1080)',
      os: "Windows 11 Home",
      battery: "Up to 7 hours",
      ports: "USB-C, USB 3.2, HDMI, USB 2.0",
      build: "Slim, lightweight everyday design",
      purpose: "Affordable, modern laptop for study, work and home",
    },
  },
  {
    id: "asus-zenbook-14",
    name: "ASUS ZenBook 14 OLED",
    category: "Laptops",
    price: 3800000,
    brand: "ASUS",
    condition: "Brand New",
    rating: 4.7,
    badge: "Premium",
    specs: ["Core i7 12th Gen", "16GB RAM", "512GB SSD", '14" OLED'],
    details: {
      type: "Premium Ultrabook",
      processor: "Intel Core i7-1260P",
      generation: "12th Generation",
      ram: "16GB LPDDR5",
      storage: "512GB NVMe SSD",
      graphics: "Intel Iris Xe (integrated)",
      display: '14" 2.8K OLED (2880 × 1800)',
      os: "Windows 11 Home",
      battery: "Up to 12 hours",
      ports: "2× Thunderbolt 4, USB-A, HDMI, microSD",
      build: "Premium metal, ultra-slim",
      purpose: "Stunning OLED ultrabook for professionals and creators",
    },
  },
  {
    id: "asus-tuf-gaming-f15",
    name: "ASUS TUF Gaming F15",
    category: "Laptops",
    price: 4200000,
    brand: "ASUS",
    condition: "Brand New",
    rating: 4.6,
    badge: "Gaming",
    specs: ["Core i7 11th Gen", "16GB RAM", "512GB SSD", "RTX 3050", '15.6" 144Hz'],
    details: {
      type: "Gaming Laptop",
      processor: "Intel Core i7-11800H (8-core)",
      generation: "11th Generation",
      ram: "16GB DDR4",
      storage: "512GB NVMe SSD",
      graphics: "NVIDIA GeForce RTX 3050 4GB (dedicated)",
      display: '15.6" Full HD (1920 × 1080) 144Hz',
      os: "Windows 11 Home",
      battery: "Up to 6 hours",
      ports: "USB-C, 3× USB-A, HDMI, Ethernet (RJ-45)",
      build: "Military-grade durable gaming chassis",
      purpose: "Affordable gaming and heavy multitasking",
    },
  },

  // ── Desktops (550k+) ────────────────────────────────────────
  {
    id: "hp-prodesk-600-g1",
    name: "HP ProDesk 600 G1 (Tower)",
    category: "Desktops",
    price: 550000,
    brand: "HP",
    condition: "UK Used",
    rating: 4.2,
    badge: "Budget pick",
    specs: ["Core i5 4th Gen", "4GB RAM", "500GB HDD", "DVD", "No monitor"],
    details: {
      type: "Desktop Tower (CPU only, no monitor)",
      processor: "Intel Core i5-4570 (quad-core)",
      generation: "4th Generation",
      ram: "4GB DDR3 (upgradable to 16GB)",
      storage: "500GB HDD",
      graphics: "Intel HD Graphics 4600 (integrated)",
      display: "No monitor included — DisplayPort / VGA output",
      os: "Windows 10 Pro",
      battery: "Not applicable (mains powered)",
      ports: "USB 3.0, USB 2.0, DisplayPort, VGA, Ethernet (RJ-45)",
      build: "Compact business-grade tower",
      purpose: "Affordable home or office desktop",
    },
  },
  {
    id: "dell-optiplex-7010-sff",
    name: "Dell OptiPlex 7010 SFF",
    category: "Desktops",
    price: 620000,
    brand: "Dell",
    condition: "UK Used",
    rating: 4.3,
    inStock: false,
    specs: ["Core i5 3rd Gen", "8GB RAM", "500GB HDD", "Compact"],
    details: {
      type: "Desktop Small Form Factor (no monitor)",
      processor: "Intel Core i5-3470 (quad-core)",
      generation: "3rd Generation",
      ram: "8GB DDR3",
      storage: "500GB HDD",
      graphics: "Intel HD Graphics 2500 (integrated)",
      display: "No monitor included — DisplayPort / VGA output",
      os: "Windows 10 Pro",
      battery: "Not applicable (mains powered)",
      ports: "USB 3.0, DisplayPort, VGA, Ethernet (RJ-45)",
      build: "Space-saving Small Form Factor",
      purpose: "Compact office desktop for everyday tasks",
    },
  },
  {
    id: "hp-280-g6-desktop",
    name: "HP 280 G6 Desktop PC",
    category: "Desktops",
    price: 1750000,
    brand: "HP",
    condition: "Brand New",
    rating: 4.5,
    specs: ["Core i5 10th Gen", "8GB RAM", "1TB HDD", "DOS", "1-year warranty"],
    details: {
      type: "Desktop Tower (no monitor)",
      processor: "Intel Core i5-10400 (6-core)",
      generation: "10th Generation",
      ram: "8GB DDR4 (upgradable to 32GB)",
      storage: "1TB HDD",
      graphics: "Intel UHD Graphics 630 (integrated)",
      display: "No monitor included — HDMI / VGA output",
      os: "FreeDOS (Windows can be installed)",
      battery: "Not applicable (mains powered)",
      ports: "USB 3.2, USB 2.0, HDMI, VGA, Ethernet (RJ-45)",
      build: "Brand-new tower with 1-year warranty",
      purpose: "New, reliable desktop for office and business",
    },
  },
  {
    id: "dell-optiplex-7090-i7",
    name: "Dell OptiPlex 7090 (i7)",
    category: "Desktops",
    price: 2650000,
    brand: "Dell",
    condition: "Brand New",
    rating: 4.6,
    specs: ["Core i7 11th Gen", "16GB RAM", "512GB SSD", "Windows 11 Pro"],
    details: {
      type: "Desktop Tower (no monitor)",
      processor: "Intel Core i7-11700 (8-core)",
      generation: "11th Generation",
      ram: "16GB DDR4",
      storage: "512GB NVMe SSD",
      graphics: "Intel UHD Graphics 750 (integrated)",
      display: "No monitor included — DisplayPort / HDMI output",
      os: "Windows 11 Pro",
      battery: "Not applicable (mains powered)",
      ports: "USB 3.2, USB-C, DisplayPort, HDMI, Ethernet (RJ-45)",
      build: "Brand-new business desktop",
      purpose: "Powerful desktop for demanding business workloads",
    },
  },

  // ── Accessories ─────────────────────────────────────────────
  {
    id: "logitech-mk270",
    name: "Logitech MK270 Wireless Combo",
    category: "Accessories",
    price: 95000,
    brand: "Logitech",
    condition: "Brand New",
    rating: 4.4,
    specs: ["Keyboard + Mouse", "2.4GHz wireless", "Long battery life"],
  },
  {
    id: "logitech-c270-webcam",
    name: "Logitech C270 HD Webcam",
    category: "Accessories",
    price: 120000,
    brand: "Logitech",
    condition: "Brand New",
    rating: 4.5,
    specs: ["720p HD", "Built-in mic", "Plug & play"],
  },
  {
    id: "laptop-backpack-grey",
    name: "Slim Laptop Backpack (Grey)",
    category: "Accessories",
    price: 80000,
    brand: "Generic",
    condition: "Brand New",
    rating: 4.6,
    badge: "New",
    specs: ['Fits up to 15.6"', "Padded laptop compartment", "Water-resistant"],
  },
  {
    id: "laptop-sleeve-grey",
    name: "Laptop Sleeve Bag (Grey)",
    category: "Accessories",
    price: 80000,
    brand: "Generic",
    condition: "Brand New",
    rating: 4.5,
    specs: ['Fits 14"–15.6"', "Slim carry handles", "Soft protective lining"],
  },
  {
    id: "lenovo-thinkbook-backpack",
    name: "Lenovo ThinkBook Backpack (Grey)",
    category: "Accessories",
    price: 80000,
    brand: "Lenovo",
    condition: "Brand New",
    rating: 4.7,
    specs: ["Padded laptop compartment", "Durable grey fabric", "Lenovo ThinkBook"],
  },
  {
    id: "laptop-charger-universal",
    name: "Universal Laptop Charger",
    category: "Power",
    price: 65000,
    brand: "Generic",
    condition: "Brand New",
    rating: 4.2,
    specs: ["Multiple tips", "65W–90W", "HP/Dell/Lenovo compatible"],
  },
  {
    id: "mercury-ups-650va",
    name: "Mercury 650VA UPS",
    category: "Power",
    price: 180000,
    brand: "Mercury",
    condition: "Brand New",
    rating: 4.3,
    specs: ["650VA / 360W", "Surge protection", "Backup for PC + router"],
  },
  {
    id: "usb-c-charger-65w",
    name: "USB-C 65W Laptop Charger",
    category: "Power",
    price: 95000,
    brand: "Generic",
    condition: "Brand New",
    rating: 4.5,
    badge: "New",
    specs: ["65W USB-C PD", "Fast charging", "Laptops, tablets & phones"],
  },
  {
    id: "laptop-charger-pin-90w",
    name: "90W Pin Laptop Charger (HP/Dell)",
    category: "Power",
    price: 80000,
    brand: "Generic",
    condition: "Brand New",
    rating: 4.3,
    specs: ["90W output", "HP / Dell / Lenovo tips", "Surge-safe"],
  },
  {
    id: "power-bank-20000",
    name: "20,000mAh Power Bank",
    category: "Power",
    price: 150000,
    brand: "Generic",
    condition: "Brand New",
    rating: 4.5,
    specs: ["20,000mAh", "Fast charge", "Dual USB + USB-C"],
  },
  {
    id: "power-bank-10000",
    name: "10,000mAh Power Bank",
    category: "Power",
    price: 90000,
    brand: "Generic",
    condition: "Brand New",
    rating: 4.4,
    specs: ["10,000mAh", "Slim & portable", "USB-C in/out"],
  },

  // ── Components (RAM & SSD upgrades) ──────────────────────────
  {
    id: "ram-ddr4-8gb-sodimm",
    name: "8GB DDR4 Laptop RAM (SODIMM)",
    category: "Components",
    price: 130000,
    brand: "Generic",
    condition: "Brand New",
    rating: 4.7,
    badge: "Upgrade",
    specs: ["8GB DDR4", "SODIMM (laptop)", "3200MHz"],
  },
  {
    id: "ram-ddr4-16gb-sodimm",
    name: "16GB DDR4 Laptop RAM (SODIMM)",
    category: "Components",
    price: 240000,
    brand: "Generic",
    condition: "Brand New",
    rating: 4.7,
    specs: ["16GB DDR4", "SODIMM (laptop)", "3200MHz"],
  },
  {
    id: "ram-ddr4-8gb-dimm",
    name: "8GB DDR4 Desktop RAM (DIMM)",
    category: "Components",
    price: 140000,
    brand: "Generic",
    condition: "Brand New",
    rating: 4.6,
    specs: ["8GB DDR4", "DIMM (desktop)", "3200MHz"],
  },
  {
    id: "ssd-nvme-500gb",
    name: "500GB NVMe M.2 SSD",
    category: "Components",
    price: 340000,
    brand: "Generic",
    condition: "Brand New",
    rating: 4.8,
    badge: "Fast",
    specs: ["500GB", "NVMe M.2", "Up to 3500MB/s"],
  },
  {
    id: "ssd-480gb-sata",
    name: "480GB SATA SSD",
    category: "Components",
    price: 220000,
    brand: "Generic",
    condition: "Brand New",
    rating: 4.7,
    specs: ['480GB', '2.5" SATA', "Up to 550MB/s"],
  },

  // ── Networking ──────────────────────────────────────────────
  {
    id: "tp-link-archer-c6",
    name: "TP-Link Archer C6 Router",
    category: "Networking",
    price: 165000,
    brand: "TP-Link",
    condition: "Brand New",
    rating: 4.6,
    badge: "New",
    specs: ["AC1200 dual-band", "4 antennas", "MU-MIMO"],
  },
  {
    id: "tp-link-tl-sg108",
    name: "TP-Link 8-Port Gigabit Switch",
    category: "Networking",
    price: 145000,
    brand: "TP-Link",
    condition: "Brand New",
    rating: 4.6,
    specs: ["8 × Gigabit ports", "Plug & play", "Metal case"],
  },

  // ── Storage ─────────────────────────────────────────────────
  {
    id: "sandisk-ssd-1tb",
    name: "SanDisk Extreme 1TB Portable SSD",
    category: "Storage",
    price: 520000,
    brand: "SanDisk",
    condition: "Brand New",
    rating: 4.8,
    specs: ["1TB", "USB-C", "Up to 1050MB/s"],
  },
  {
    id: "wd-elements-1tb-hdd",
    name: "WD Elements 1TB External HDD",
    category: "Storage",
    price: 220000,
    brand: "Western Digital",
    condition: "Brand New",
    rating: 4.6,
    specs: ["1TB", "USB 3.0", "Plug & play"],
  },
  {
    id: "kingston-240gb-ssd",
    name: "Kingston A400 240GB SSD",
    category: "Storage",
    price: 130000,
    brand: "Kingston",
    condition: "Brand New",
    rating: 4.7,
    specs: ["240GB SATA SSD", "Up to 500MB/s", "Speeds up any laptop"],
  },
  {
    id: "sandisk-flash-64gb",
    name: "SanDisk 64GB Flash Drive",
    category: "Storage",
    price: 55000,
    brand: "SanDisk",
    condition: "Brand New",
    rating: 4.6,
    specs: ["64GB", "USB 3.0", "Plug & play"],
  },
  {
    id: "kingston-flash-32gb",
    name: "Kingston 32GB Flash Drive",
    category: "Storage",
    price: 45000,
    brand: "Kingston",
    condition: "Brand New",
    rating: 4.5,
    specs: ["32GB", "USB 2.0", "Compact"],
  },
  {
    id: "microsd-64gb",
    name: "64GB MicroSD Card + Adapter",
    category: "Storage",
    price: 65000,
    brand: "Generic",
    condition: "Brand New",
    rating: 4.5,
    specs: ["64GB", "Class 10", "SD adapter included"],
  },

  // ── More brand products ─────────────────────────────────────
  // Kingston
  { id: "kingston-ssd-480gb", name: "Kingston A400 480GB SSD", category: "Storage", price: 220000, brand: "Kingston", condition: "Brand New", rating: 4.7, specs: ["480GB SATA SSD", "Up to 500MB/s", "2.5\" laptop/desktop"] },
  { id: "kingston-nvme-500gb", name: "Kingston NV2 500GB NVMe SSD", category: "Components", price: 280000, brand: "Kingston", condition: "Brand New", rating: 4.8, badge: "Fast", specs: ["500GB", "NVMe M.2", "Up to 3500MB/s"] },
  { id: "kingston-flash-64gb", name: "Kingston 64GB Flash Drive", category: "Storage", price: 38000, brand: "Kingston", condition: "Brand New", rating: 4.5, specs: ["64GB", "USB 3.2", "Compact"] },
  // Logitech
  { id: "logitech-m170-mouse", name: "Logitech M170 Wireless Mouse", category: "Accessories", price: 45000, brand: "Logitech", condition: "Brand New", rating: 4.5, specs: ["2.4GHz wireless", "Plug & play", "Long battery life"] },
  { id: "logitech-k380-keyboard", name: "Logitech K380 Bluetooth Keyboard", category: "Accessories", price: 130000, brand: "Logitech", condition: "Brand New", rating: 4.6, specs: ["Bluetooth", "Multi-device", "Compact"] },
  { id: "logitech-h111-headset", name: "Logitech H111 Stereo Headset", category: "Accessories", price: 70000, brand: "Logitech", condition: "Brand New", rating: 4.4, specs: ["3.5mm", "Mic + volume control", "Lightweight"] },
  // Mercury
  { id: "mercury-ups-850va", name: "Mercury 850VA UPS", category: "Power", price: 230000, brand: "Mercury", condition: "Brand New", rating: 4.4, specs: ["850VA / 480W", "Surge protection", "Backup for PC + router"] },
  { id: "mercury-power-bank", name: "Mercury 10,000mAh Power Bank", category: "Power", price: 95000, brand: "Mercury", condition: "Brand New", rating: 4.3, specs: ["10,000mAh", "Dual USB", "Fast charge"] },
  // SanDisk
  { id: "sandisk-flash-128gb", name: "SanDisk Ultra 128GB Flash Drive", category: "Storage", price: 55000, brand: "SanDisk", condition: "Brand New", rating: 4.7, specs: ["128GB", "USB 3.0", "Up to 130MB/s"] },
  { id: "sandisk-microsd-128gb", name: "SanDisk 128GB MicroSD Card", category: "Storage", price: 65000, brand: "SanDisk", condition: "Brand New", rating: 4.7, specs: ["128GB", "Class 10 / U1", "SD adapter included"] },
  { id: "sandisk-ssd-500gb", name: "SanDisk SSD Plus 500GB", category: "Storage", price: 320000, brand: "SanDisk", condition: "Brand New", rating: 4.7, specs: ["500GB", "Portable SSD", "USB-C"] },
  // TP-Link
  { id: "tp-link-archer-c20", name: "TP-Link Archer C20 Router", category: "Networking", price: 110000, brand: "TP-Link", condition: "Brand New", rating: 4.5, specs: ["AC750 dual-band", "3 antennas", "Easy setup"] },
  { id: "tp-link-re200-extender", name: "TP-Link RE200 WiFi Extender", category: "Networking", price: 95000, brand: "TP-Link", condition: "Brand New", rating: 4.5, badge: "New", specs: ["AC750", "Extends Wi-Fi range", "Plug-in"] },
  // Western Digital
  { id: "wd-elements-2tb", name: "WD Elements 2TB External HDD", category: "Storage", price: 320000, brand: "Western Digital", condition: "Brand New", rating: 4.7, specs: ["2TB", "USB 3.0", "Plug & play"] },
  { id: "wd-passport-1tb", name: "WD My Passport 1TB", category: "Storage", price: 260000, brand: "Western Digital", condition: "Brand New", rating: 4.7, specs: ["1TB", "USB 3.0", "Password protection"] },
  { id: "wd-blue-ssd-500gb", name: "WD Blue 500GB SSD", category: "Storage", price: 300000, brand: "Western Digital", condition: "Brand New", rating: 4.7, specs: ["500GB", "2.5\" SATA", "Reliable upgrade"] },

  // ── Extra stock (web images; sync to backend catalog before enabling checkout) ──
  { id: "lenovo-thinkpad-t480", name: "Lenovo ThinkPad T480", category: "Laptops", price: 950000, oldPrice: 1100000, brand: "Lenovo", condition: "UK Used", rating: 4.6, badge: "Popular", image: "/web/photo-1496181133206-80ce9b88a853.jpg", specs: ["Core i5 8th Gen", "8GB RAM", "256GB SSD", "14\" FHD", "Windows 11"] },
  { id: "macbook-air-2017", name: "Apple MacBook Air 13\" (2017)", category: "Laptops", price: 1900000, brand: "Apple", condition: "Refurbished", rating: 4.7, image: "/web/photo-1517336714731-489689fd1ca8.jpg", specs: ["Core i5", "8GB RAM", "128GB SSD", "13.3\" display", "macOS"] },
  { id: "dell-optiplex-3070-micro", name: "Dell OptiPlex 3070 Micro", category: "Desktops", price: 900000, brand: "Dell", condition: "UK Used", rating: 4.5, image: "/web/photo-1544197150-b99a580bb7a8.jpg", specs: ["Core i5 9th Gen", "8GB RAM", "256GB SSD", "Tiny form factor", "Windows 11"] },
  { id: "hp-prodesk-400-g5", name: "HP ProDesk 400 G5 Tower", category: "Desktops", price: 1100000, brand: "HP", condition: "Refurbished", rating: 4.5, image: "/web/photo-1587202372775-e229f172b9d7.jpg", specs: ["Core i5 8th Gen", "8GB RAM", "1TB HDD", "Tower", "Windows 11"] },
  { id: "kingston-fury-8gb-ddr4", name: "Kingston FURY 8GB DDR4 RAM", category: "Components", price: 150000, brand: "Kingston", condition: "Brand New", rating: 4.8, badge: "New", image: "/web/photo-1618410320928-25228d811631.jpg", specs: ["8GB DDR4", "3200MHz", "Desktop DIMM"] },
  { id: "crucial-mx500-500gb", name: "Crucial MX500 500GB SSD", category: "Components", price: 260000, brand: "Crucial", condition: "Brand New", rating: 4.8, image: "/web/photo-1625842268584-8f3296236761.jpg", specs: ["500GB", "2.5\" SATA", "Fast boot upgrade"] },
  { id: "anker-powerbank-20000", name: "Anker 20,000mAh Power Bank", category: "Power", price: 185000, brand: "Anker", condition: "Brand New", rating: 4.7, badge: "Bestseller", image: "/web/photo-1609091839311-d5365f9ff1c5.jpg", specs: ["20,000mAh", "USB-C PD", "Fast charge"] },
  { id: "usb-c-65w-charger", name: "65W USB-C Laptop Charger", category: "Power", price: 90000, brand: "Generic", condition: "Brand New", rating: 4.4, image: "/web/photo-1588681664899-f142ff2dc9b1.jpg", specs: ["65W", "USB-C PD", "Universal laptops"] },
  { id: "logitech-m170-mouse", name: "Logitech M170 Wireless Mouse", category: "Accessories", price: 45000, brand: "Logitech", condition: "Brand New", rating: 4.6, image: "/web/photo-1591488320449-011701bb6704.jpg", specs: ["Wireless", "USB receiver", "18-month battery"] },
  { id: "redragon-k552-keyboard", name: "Redragon K552 Mechanical Keyboard", category: "Accessories", price: 135000, brand: "Redragon", condition: "Brand New", rating: 4.7, badge: "Gaming", image: "/web/photo-1563770660941-20978e870e26.jpg", specs: ["Mechanical", "RGB backlight", "Compact TKL"] },
  { id: "hd-1080p-webcam", name: "1080p HD Webcam", category: "Accessories", price: 120000, brand: "Generic", condition: "Brand New", rating: 4.4, image: "/web/photo-1546027658-7aa750153465.jpg", specs: ["1080p", "Built-in mic", "Clip-on"] },
  { id: "tp-link-archer-c6", name: "TP-Link Archer C6 Router", category: "Networking", price: 165000, brand: "TP-Link", condition: "Brand New", rating: 4.6, image: "/web/photo-1601737487795-dab272f52420.jpg", specs: ["AC1200 dual-band", "4 antennas", "MU-MIMO"] },
  { id: "seagate-expansion-1tb", name: "Seagate Expansion 1TB HDD", category: "Storage", price: 250000, brand: "Seagate", condition: "Brand New", rating: 4.7, image: "/web/photo-1550009158-9ebf69173e03.jpg", specs: ["1TB", "USB 3.0", "Plug & play"] },
  { id: "sandisk-ultra-128gb-flash", name: "SanDisk Ultra 128GB Flash Drive", category: "Storage", price: 60000, brand: "SanDisk", condition: "Brand New", rating: 4.7, image: "/web/photo-1558618666-fcd25c85cd64.jpg", specs: ["128GB", "USB 3.0", "Up to 130MB/s"] },
];

export const productCategories = [
  "All",
  "Laptops",
  "Desktops",
  "Components",
  "Power",
  "Accessories",
  "Networking",
  "Storage",
] as const;

export type Service = {
  slug: string;
  icon: string;
  title: string;
  summary: string;
  bullets: string[];
  startingFrom?: number;
  image?: string; // banner photo communicating the service
};

export const services: Service[] = [
  {
    slug: "web-development",
    icon: "web",
    title: "Website Development",
    summary:
      "Fast, modern, mobile-friendly websites that win customers — business sites, e-commerce, and web apps.",
    bullets: ["Business & landing sites", "E-commerce stores", "SEO & analytics", "Maintenance plans"],
    startingFrom: 500000,
    image: "/web/photo-1547658719-da2b51169166.jpg", // web design / wireframe
  },
  {
    slug: "mobile-apps",
    icon: "mobile",
    title: "Mobile App Development",
    summary: "Android & iOS apps that put your service in your customers' pockets.",
    bullets: ["Cross-platform apps", "Push notifications", "Payments integration", "App store launch"],
    startingFrom: 2500000,
    image: "/web/photo-1512941937669-90a1b58e7e9c.jpg", // smartphone app
  },
  {
    slug: "software-systems",
    icon: "software",
    title: "Software Systems",
    summary: "Custom systems that run your business — School, POS, Inventory & SACCO management.",
    bullets: ["School management", "POS & inventory", "SACCO systems", "Setup + support plans"],
    image: "/web/photo-1551288049-bebda4e38f71.jpg", // dashboard / analytics
  },
  {
    slug: "repairs-support",
    icon: "repair",
    title: "Repairs & IT Support",
    summary: "Laptop & desktop repair, upgrades, OS installation and ongoing IT support.",
    bullets: ["Hardware repair", "OS & software installation", "Upgrades (RAM/SSD)", "Remote & onsite support"],
    startingFrom: 30000,
    image: "/web/photo-1581092160562-40aa08e78837.jpg", // repair workbench
  },
  {
    slug: "networking",
    icon: "wifi",
    title: "Networking Services",
    summary: "Reliable internet & networks for homes, offices and institutions.",
    bullets: ["Wi-Fi setup", "Office LAN/cabling", "CCTV & access control", "Network security"],
    image: "/web/photo-1601737487795-dab272f52420.jpg", // router / networking
  },
  {
    slug: "digital-learning",
    icon: "learn",
    title: "Digital Learning Platforms",
    summary: "We build online learning platforms — and run our own academy too.",
    bullets: ["Course platforms (LMS)", "Video hosting", "Certificates", "Payments"],
    image: "/web/photo-1516321318423-f06f85e504b3.jpg", // online learning
  },
];

export type Lesson = {
  title: string;
  minutes: number;
  free?: boolean; // free lessons are playable without payment
  preview?: string; // video URL for free/preview lessons
  youtube?: string; // YouTube video id for teaching videos
};

export type LiveClass = {
  id: string;
  title: string;
  topic: string;
  level: "Beginner" | "Intermediate" | "Advanced";
  date: string; // ISO date-time
  durationMins: number;
  host: string;
  mode: "Online" | "In-class";
  price: number; // 0 = free
};

// Upcoming live classes (instructor-led sessions learners register for).
export const liveClasses: LiveClass[] = [
  {
    id: "live-computer-basics",
    title: "Computer Basics — Live Starter Class",
    topic: "Mouse, keyboard, files & getting online — live Q&A",
    level: "Beginner",
    date: "2026-07-05T15:00:00+03:00",
    durationMins: 90,
    host: "Agaba Geofrey",
    mode: "Online",
    price: 0,
  },
  {
    id: "live-excel",
    title: "Excel for Work & Business (Live)",
    topic: "Formulas, budgets & charts with hands-on practice",
    level: "Beginner",
    date: "2026-07-12T16:00:00+03:00",
    durationMins: 120,
    host: "Agaba Geofrey",
    mode: "Online",
    price: 20000,
  },
  {
    id: "live-online-safety",
    title: "Internet & Mobile Money Safety (Live)",
    topic: "Stay safe online, avoid scams, use MoMo securely",
    level: "Beginner",
    date: "2026-07-19T15:00:00+03:00",
    durationMins: 60,
    host: "Online Tech Uganda",
    mode: "Online",
    price: 0,
  },
  {
    id: "live-web-intro",
    title: "Intro to Websites & Tech Careers (In-class)",
    topic: "How websites work + a path into tech — at our Kampala office",
    level: "Beginner",
    date: "2026-07-26T10:00:00+03:00",
    durationMins: 180,
    host: "Agaba Geofrey",
    mode: "In-class",
    price: 30000,
  },
];

export type CourseMaterial = { title: string; file: string };
export type QuizQuestion = { q: string; options: string[]; answer: number };

export type Course = {
  slug: string;
  title: string;
  level: "Beginner" | "Intermediate" | "Advanced";
  lessons: number;
  hours: number;
  price: number;
  blurb: string;
  emoji: string;
  syllabus: Lesson[];
  materials?: CourseMaterial[];
  notes?: CourseMaterial[]; // readable chapter notes (Word docs) shown in the reader
  quiz?: QuizQuestion[];
  unlockCode?: string; // code sent to the learner after MoMo payment
  sampleVideo?: string; // video played for unlocked paid lessons
};

// Per-lesson unlock price (UGX), 1,000–5,000 depending on lesson length.
export function lessonPrice(minutes: number): number {
  if (minutes <= 10) return 1000;
  if (minutes <= 18) return 2000;
  if (minutes <= 28) return 3000;
  if (minutes <= 40) return 4000;
  return 5000;
}

export const courses: Course[] = [
  {
    slug: "computer-basics",
    title: "Computer Basics for Everyone",
    level: "Beginner",
    lessons: 22,
    hours: 6,
    price: 50000,
    blurb:
      "Start from zero — mouse, keyboard, files, internet and staying safe online. Perfect for students and mature learners.",
    emoji: "laptop",
    syllabus: [
      { title: "Computer basics — full beginner tutorial (video)", minutes: 60, free: true, youtube: "y2kg3MOk1sY" },
      { title: "Meet the computer: parts & switching on", minutes: 8, free: true, preview: "/videos/v-01.mp4" },
      // Follows the written notes: what a computer is → hardware → operating it.
      { title: "What a computer is, its types & everyday uses", minutes: 14 },
      { title: "Inside the machine: CPU, RAM & storage", minutes: 16 },
      { title: "Input & output devices explained", minutes: 12 },
      { title: "Starting up & shutting down properly", minutes: 8 },
      { title: "Using the mouse & keyboard confidently", minutes: 15 },
      { title: "The desktop: icons, windows & menus", minutes: 18 },
      { title: "Working with several windows at once", minutes: 12 },
      { title: "Files & folders: save, find & organise", minutes: 22 },
      { title: "Copy, cut, paste & rename", minutes: 15 },
      { title: "Deleting files & the Recycle Bin", minutes: 10 },
      { title: "Using a USB flash drive safely", minutes: 12 },
      { title: "Backing up your important work", minutes: 14 },
      { title: "Installing & uninstalling programs", minutes: 16 },
      { title: "Settings: volume, brightness, date & time", minutes: 10 },
      { title: "Connecting to Wi-Fi", minutes: 12 },
      { title: "Using a web browser", minutes: 14 },
      { title: "Staying safe from viruses & malware", minutes: 18 },
      { title: "Printing documents & photos", minutes: 12 },
      { title: "Fixing common problems yourself", minutes: 16 },
      { title: "Caring for your computer: habits & maintenance", minutes: 12 },
    ],
    unlockCode: "CB-2026",
    sampleVideo: "/videos/v-05.mp4",
    materials: [{ title: "Computer Basics — course notes (PDF)", file: "/courses/computer-basics-notes.pdf" }],
    notes: [
      { title: "Course Roadmap & Learning Path", file: "/courses/computer-basics-roadmap.docx" },
      { title: "Chapter 1 — Introduction to Computers", file: "/courses/computer-basics-ch1.docx" },
      { title: "Chapter 2 — Computer Hardware & Internal Components", file: "/courses/computer-basics-ch2.docx" },
    ],
    quiz: [
      { q: "Which device do you use to move the pointer on screen?", options: ["Keyboard", "Mouse", "Monitor", "Printer"], answer: 1 },
      { q: "What is used to type text into a computer?", options: ["Mouse", "Speaker", "Keyboard", "Webcam"], answer: 2 },
      { q: "Where are your saved documents kept?", options: ["Files & folders", "The mouse", "The screen", "The power button"], answer: 0 },
      { q: "To stay safe online you should…", options: ["Share your password", "Click every link", "Use strong passwords", "Ignore updates"], answer: 2 },
      { q: "What does CPU stand for?", options: ["Central Processing Unit", "Computer Power Unit", "Central Print Unit", "Control Panel Unit"], answer: 0 },
      { q: "Which of these is an output device?", options: ["Keyboard", "Mouse", "Monitor", "Microphone"], answer: 2 },
      { q: "Which shortcut saves your work?", options: ["Ctrl + S", "Ctrl + P", "Ctrl + X", "Ctrl + A"], answer: 0 },
      { q: "Turning the computer off correctly is called…", options: ["Crashing", "Shutting down", "Refreshing", "Logging in"], answer: 1 },
      { q: "A folder is mainly used to…", options: ["Play music", "Organise files", "Print pages", "Delete viruses"], answer: 1 },
      { q: "Which part stores your files permanently?", options: ["RAM", "The screen", "Hard drive / SSD", "The mouse"], answer: 2 },
    ],
  },
  {
    slug: "microsoft-office",
    // NOTE: lessons must equal syllabus.length — the storefront prints both.
    title: "Microsoft Office Mastery",
    level: "Beginner",
    lessons: 35,
    hours: 14,
    price: 80000,
    blurb: "Step by step through Word, Excel, PowerPoint, Publisher & Access — from beginner to confident, with hands-on practice.",
    emoji: "office",
    syllabus: [
      { title: "Step 1 — Getting started with Microsoft Office", minutes: 10, free: true, preview: "/videos/v-06.mp4" },
      { title: "Step 2 — Microsoft Word: beginner tutorial", minutes: 60, free: true, youtube: "v3zc3bXL5pc" },
      // One app at a time, start to finish — no jumping back and forth.
      { title: "Step 3 — Word: formatting, tables & images", minutes: 25 },
      { title: "Step 4 — Word: headers, footers & page numbers", minutes: 15 },
      { title: "Step 5 — Word: styles & templates", minutes: 18 },
      { title: "Step 6 — Word: columns & page layout", minutes: 16 },
      { title: "Step 7 — Word: table of contents & references", minutes: 20 },
      { title: "Step 8 — Word: track changes & comments", minutes: 14 },
      { title: "Step 9 — Word: mail merge & printing", minutes: 22 },
      { title: "Step 10 — Word: shortcuts & productivity tips", minutes: 12 },
      { title: "Step 11 — Microsoft Excel: beginner tutorial", minutes: 60, free: true, youtube: "Vl0H-qTclOg" },
      { title: "Step 12 — Excel: formulas & functions", minutes: 30 },
      { title: "Step 13 — Excel: sorting & filtering data", minutes: 16 },
      { title: "Step 14 — Excel: IF, VLOOKUP & logical functions", minutes: 30 },
      { title: "Step 15 — Excel: charts & simple budgets", minutes: 28 },
      { title: "Step 16 — Excel: conditional formatting", minutes: 16 },
      { title: "Step 17 — Excel: data validation & drop-downs", minutes: 18 },
      { title: "Step 18 — Excel: pivot tables made simple", minutes: 28 },
      { title: "Step 19 — Excel: printing large spreadsheets", minutes: 12 },
      { title: "Step 20 — Microsoft PowerPoint: beginner tutorial", minutes: 60, free: true, youtube: "KqgyvGxISxk" },
      { title: "Step 21 — PowerPoint: building slides & using themes", minutes: 22 },
      { title: "Step 22 — PowerPoint: animations & transitions", minutes: 20 },
      { title: "Step 23 — PowerPoint: adding media & audio", minutes: 16 },
      { title: "Step 24 — PowerPoint: presenter view & delivering your talk", minutes: 18 },
      { title: "Step 25 — Microsoft Publisher: flyers & brochures", minutes: 30 },
      { title: "Step 26 — Publisher: business cards & letterheads", minutes: 18 },
      { title: "Step 27 — Publisher: newsletters & multi-page layouts", minutes: 22 },
      { title: "Step 28 — Microsoft Access: beginner database tutorial", minutes: 60, free: true, youtube: "hMuSHYfG7H8" },
      { title: "Step 29 — Access: creating tables & forms", minutes: 26 },
      { title: "Step 30 — Access: table relationships", minutes: 20 },
      { title: "Step 31 — Access: building queries", minutes: 24 },
      { title: "Step 32 — Access: reports & printing", minutes: 18 },
      { title: "Step 33 — Saving to OneDrive & the cloud", minutes: 12 },
      { title: "Step 34 — Sharing & working with others", minutes: 14 },
      { title: "Step 35 — Final project: a complete business document set", minutes: 40 },
    ],
    unlockCode: "OFFICE-2026",
    sampleVideo: "/videos/v-06.mp4",
    materials: [{ title: "MS Office — practice workbook & notes (PDF)", file: "/courses/microsoft-office-notes.pdf" }],
    quiz: [
      { q: "Which app is best for typing a formal letter?", options: ["Excel", "Word", "PowerPoint", "Paint"], answer: 1 },
      { q: "In Excel, a formula always starts with…", options: ["#", "@", "=", "!"], answer: 2 },
      { q: "Which app is used to create slide presentations?", options: ["Word", "Excel", "PowerPoint", "Notepad"], answer: 2 },
      { q: "To make text bold you press…", options: ["Ctrl + B", "Ctrl + S", "Ctrl + P", "Ctrl + Z"], answer: 0 },
      { q: "In Excel, a single box is called a…", options: ["Cell", "Slide", "Page", "Paragraph"], answer: 0 },
      { q: "Which shortcut undoes your last action?", options: ["Ctrl + Y", "Ctrl + Z", "Ctrl + V", "Ctrl + B"], answer: 1 },
      { q: "Which Office app is best for calculations & budgets?", options: ["Word", "Excel", "PowerPoint", "Access"], answer: 1 },
      { q: "To print a document you press…", options: ["Ctrl + P", "Ctrl + S", "Ctrl + D", "Ctrl + F"], answer: 0 },
      { q: "Microsoft Access is used to manage…", options: ["Photos", "Databases", "Videos", "Music"], answer: 1 },
      { q: "In Word, where do you change the font size?", options: ["Home tab", "Power button", "Taskbar", "Start menu"], answer: 0 },
      { q: "Which app is best for designing flyers, cards & brochures?", options: ["Word", "Excel", "Publisher", "Access"], answer: 2 },
    ],
  },
  {
    slug: "internet-email",
    title: "Internet, Email & Online Safety",
    level: "Beginner",
    lessons: 14,
    hours: 4,
    price: 40000,
    blurb: "Browse, search, send email, use mobile money safely and avoid online scams.",
    emoji: "globe",
    syllabus: [
      { title: "Internet & online safety — full tutorial (video)", minutes: 30, free: true, youtube: "aO858HyFbKI" },
      { title: "Email basics — how email works (video)", minutes: 20, free: true, youtube: "0kIaw1yhUVM" },
      // Browsing → searching → email → communicating → staying safe.
      { title: "Web browsers compared (Chrome, Edge, Firefox)", minutes: 12 },
      { title: "Bookmarks, tabs & history", minutes: 12 },
      { title: "Searching Google effectively", minutes: 18 },
      { title: "Downloading & uploading files", minutes: 14 },
      { title: "Creating a Gmail account step by step", minutes: 18 },
      { title: "Writing professional emails", minutes: 16 },
      { title: "Attachments, CC & BCC", minutes: 12 },
      { title: "Organising your inbox with labels & folders", minutes: 14 },
      { title: "Video calls: Zoom, Google Meet & WhatsApp", minutes: 18 },
      { title: "Mobile Money: sending & receiving safely", minutes: 20 },
      { title: "Recognising phishing & online scams", minutes: 20 },
      { title: "Protecting your privacy & personal data", minutes: 18 },
    ],
    unlockCode: "NET-2026",
    sampleVideo: "/videos/v-07.mp4",
    materials: [{ title: "Internet & Online Safety — notes (PDF)", file: "/courses/internet-email-notes.pdf" }],
    quiz: [
      { q: "A safe password should be…", options: ["Your name", "12345", "Long & unique", "Your phone number"], answer: 2 },
      { q: "An email address always contains…", options: ["@", "#", "&", "%"], answer: 0 },
      { q: "If a message says you won money you never entered for, it is likely…", options: ["True", "A scam", "From your bank", "Safe to click"], answer: 1 },
      { q: "Before sending Mobile Money you should…", options: ["Confirm the number", "Share your PIN", "Rush", "Ignore the amount"], answer: 0 },
      { q: "A website address (like onlinetechug.com) is called a…", options: ["URL", "PIN", "CPU", "RAM"], answer: 0 },
      { q: "To open websites you use a…", options: ["Web browser", "Calculator", "Printer", "Speaker"], answer: 0 },
      { q: "You should NEVER share your…", options: ["Name", "PIN / password", "Photo", "Email address"], answer: 1 },
      { q: "WWW stands for…", options: ["World Wide Web", "Wide World Website", "Web World Wide", "World Web Wide"], answer: 0 },
      { q: "A link from an unknown sender you should…", options: ["Click quickly", "Not click", "Forward to all", "Reply with your PIN"], answer: 1 },
      { q: "Antivirus software helps to…", options: ["Type faster", "Protect from viruses", "Save money", "Print faster"], answer: 1 },
    ],
  },
  {
    slug: "typing-skills",
    title: "Fast & Accurate Typing",
    level: "Beginner",
    lessons: 13,
    hours: 4,
    price: 35000,
    blurb: "Build real typing speed with guided drills — a skill every computer user needs.",
    emoji: "keyboard",
    syllabus: [
      { title: "Learn to touch type — full tutorial (video)", minutes: 60, free: true, youtube: "bEKQQvMF8QE" },
      { title: "Home row & correct finger placement", minutes: 9, free: true, preview: "/videos/v-04.mp4" },
      // Learn the keys → build accuracy → then build speed. Accuracy before speed.
      { title: "Top & bottom rows", minutes: 12 },
      { title: "Numbers & symbols", minutes: 15 },
      { title: "Punctuation & capital letters", minutes: 12 },
      { title: "Common words & short phrases", minutes: 14 },
      { title: "Typing without looking at the keys", minutes: 18 },
      { title: "Daily drills that build muscle memory", minutes: 20 },
      { title: "Accuracy first: cutting your mistakes", minutes: 20 },
      { title: "Building speed (words per minute)", minutes: 22 },
      { title: "Typing full paragraphs & documents", minutes: 25 },
      { title: "Keyboard shortcuts for faster work", minutes: 12 },
      { title: "Typing test & tracking your progress", minutes: 18 },
    ],
    unlockCode: "TYPE-2026",
    sampleVideo: "/videos/v-08.mp4",
    materials: [{ title: "Typing — drills & finger guide (PDF)", file: "/courses/typing-skills-notes.pdf" }],
    quiz: [
      { q: "Correct typing posture means…", options: ["Slouching", "Wrists straight, sit up", "One finger only", "Looking at keys"], answer: 1 },
      { q: "The 'home row' keys for the left hand are…", options: ["QWER", "ASDF", "ZXCV", "1234"], answer: 1 },
      { q: "Typing speed is measured in…", options: ["KPH", "WPM", "MB", "GHz"], answer: 1 },
      { q: "For accuracy you should…", options: ["Type fast & ignore errors", "Look at the keyboard", "Practice steadily", "Use one hand"], answer: 2 },
      { q: "The home row keys for the right hand are…", options: ["JKL;", "UIOP", "NM,.", "5678"], answer: 0 },
      { q: "Which key do your thumbs press?", options: ["Enter", "Spacebar", "Shift", "Tab"], answer: 1 },
      { q: "'Touch typing' means typing…", options: ["Very slowly", "Without looking at the keys", "With one hand", "Only numbers"], answer: 1 },
      { q: "Which finger usually presses the F key?", options: ["Left index", "Right thumb", "Left pinky", "Right index"], answer: 0 },
      { q: "To type a capital letter you hold…", options: ["Shift", "Tab", "Ctrl", "Alt"], answer: 0 },
      { q: "The best way to improve typing is…", options: ["Never practice", "Regular practice", "Looking down", "Using two fingers"], answer: 1 },
    ],
  },
];

export const stats = [
  { value: "500+", label: "Devices sold" },
  { value: "120+", label: "Websites & systems delivered" },
  { value: "1,000+", label: "Learners trained" },
  { value: "4.8/5", label: "Customer rating" },
];

export const whyUs = [
  {
    icon: "shield",
    title: "Genuine & guaranteed",
    body: "Quality-checked devices with warranty, and honest advice before you buy.",
  },
  {
    icon: "truck",
    title: "Countrywide delivery",
    body: "Fast delivery across Kampala and all major towns in Uganda.",
  },
  {
    icon: "chat",
    title: "Real human support",
    body: "Talk to us on WhatsApp or call — before and after your purchase.",
  },
  {
    icon: "card",
    title: "Flexible payments",
    body: "Mobile Money, cash on delivery and bank transfer accepted.",
  },
];
