// Auto-generated by scripts/product-views.mjs — product image gallery sources.
export const productImages: Record<string, string[]> = {
  "asus-rog-strix-g15": [
    "/products/asus-rog-strix-g15.webp",
    "/products/asus-rog-strix-g15-2.webp",
    "/products/asus-rog-strix-g15-3.webp"
  ],
  "asus-tuf-gaming-f15": [
    "/products/asus-tuf-gaming-f15.webp",
    "/products/asus-tuf-gaming-f15-2.webp",
    "/products/asus-tuf-gaming-f15-3.webp"
  ],
  "asus-vivobook-15": [
    "/products/asus-vivobook-15.webp",
    "/products/asus-vivobook-15-2.webp",
    "/products/asus-vivobook-15-3.webp"
  ],
  "asus-zenbook-14": [
    "/products/asus-zenbook-14.webp",
    "/products/asus-zenbook-14-2.webp",
    "/products/asus-zenbook-14-3.webp"
  ],
  "dell-latitude-7390": [
    "/products/dell-latitude-7390.webp",
    "/products/dell-latitude-7390-2.webp",
    "/products/dell-latitude-7390-3.webp"
  ],
  "dell-latitude-7420": [
    "/products/dell-latitude-7420.webp",
    "/products/dell-latitude-7420-2.webp",
    "/products/dell-latitude-7420-3.webp"
  ],
  "dell-latitude-e6440": [
    "/products/dell-latitude-e6440.webp",
    "/products/dell-latitude-e6440-2.webp",
    "/products/dell-latitude-e6440-3.webp"
  ],
  "dell-latitude-e7270": [
    "/products/dell-latitude-e7270.webp",
    "/products/dell-latitude-e7270-2.webp",
    "/products/dell-latitude-e7270-3.webp"
  ],
  "dell-optiplex-7010-sff": [
    "/products/dell-optiplex-7010-sff.webp",
    "/products/dell-optiplex-7010-sff-2.webp",
    "/products/dell-optiplex-7010-sff-3.webp"
  ],
  "dell-optiplex-7090-i7": [
    "/products/dell-optiplex-7090-i7.webp",
    "/products/dell-optiplex-7090-i7-2.webp",
    "/products/dell-optiplex-7090-i7-3.webp"
  ],
  "dell-xps-13-9310": [
    "/products/dell-xps-13-9310.webp",
    "/products/dell-xps-13-9310-2.webp",
    "/products/dell-xps-13-9310-3.webp"
  ],
  "dell-xps-15-9520": [
    "/products/dell-xps-15-9520.webp",
    "/products/dell-xps-15-9520-2.webp",
    "/products/dell-xps-15-9520-3.webp"
  ],
  "hp-280-g6-desktop": [
    "/products/hp-280-g6-desktop.webp",
    "/products/hp-280-g6-desktop-2.webp",
    "/products/hp-280-g6-desktop-3.webp"
  ],
  "hp-elitebook-840-g1": [
    "/products/hp-elitebook-840-g1.webp",
    "/products/hp-elitebook-840-g1-2.webp",
    "/products/hp-elitebook-840-g1-3.webp"
  ],
  "hp-elitebook-840-g3": [
    "/products/hp-elitebook-840-g3.webp",
    "/products/hp-elitebook-840-g3-2.webp",
    "/products/hp-elitebook-840-g3-3.webp"
  ],
  "hp-elitebook-840-g8": [
    "/products/hp-elitebook-840-g8.webp",
    "/products/hp-elitebook-840-g8-2.webp",
    "/products/hp-elitebook-840-g8-3.webp"
  ],
  "hp-pavilion-x360-13": [
    "/products/hp-pavilion-x360-13.webp",
    "/products/hp-pavilion-x360-13-2.webp",
    "/products/hp-pavilion-x360-13-3.webp"
  ],
  "hp-probook-640-g2": [
    "/products/hp-probook-640-g2.webp",
    "/products/hp-probook-640-g2-2.webp",
    "/products/hp-probook-640-g2-3.webp"
  ],
  "hp-prodesk-600-g1": [
    "/products/hp-prodesk-600-g1.webp",
    "/products/hp-prodesk-600-g1-2.webp",
    "/products/hp-prodesk-600-g1-3.webp"
  ],
  "hp-spectre-x360-14": [
    "/products/hp-spectre-x360-14.webp",
    "/products/hp-spectre-x360-14-2.webp",
    "/products/hp-spectre-x360-14-3.webp"
  ],
  "kingston-240gb-ssd": [
    "/products/kingston-240gb-ssd.webp",
    "/products/kingston-240gb-ssd-2.webp",
    "/products/kingston-240gb-ssd-3.webp"
  ],
  "kingston-flash-32gb": [
    "/products/kingston-flash-32gb.webp"
  ],
  "kingston-flash-64gb": [
    "/products/kingston-flash-64gb.webp",
    "/products/kingston-flash-64gb-2.webp",
    "/products/kingston-flash-64gb-3.webp"
  ],
  "kingston-nvme-500gb": [
    "/products/kingston-nvme-500gb.webp",
    "/products/kingston-nvme-500gb-2.webp",
    "/products/kingston-nvme-500gb-3.webp"
  ],
  "kingston-ssd-480gb": [
    "/products/kingston-ssd-480gb.webp",
    "/products/kingston-ssd-480gb-2.webp",
    "/products/kingston-ssd-480gb-3.webp"
  ],
  "laptop-backpack-grey": [
    "/products/laptop-backpack-grey.webp"
  ],
  "laptop-charger-pin-90w": [
    "/products/laptop-charger-pin-90w.webp"
  ],
  "laptop-charger-universal": [
    "/products/laptop-charger-universal.webp",
    "/products/laptop-charger-universal-2.webp",
    "/products/laptop-charger-universal-3.webp"
  ],
  "laptop-sleeve-grey": [
    "/products/laptop-sleeve-grey.webp",
    "/products/laptop-sleeve-grey-2.webp",
    "/products/laptop-sleeve-grey-3.webp"
  ],
  "lenovo-legion-5-15": [
    "/products/lenovo-legion-5-15.webp",
    "/products/lenovo-legion-5-15-2.webp",
    "/products/lenovo-legion-5-15-3.webp"
  ],
  "lenovo-thinkbook-backpack": [
    "/products/lenovo-thinkbook-backpack.webp"
  ],
  "lenovo-thinkpad-t14": [
    "/products/lenovo-thinkpad-t14.webp",
    "/products/lenovo-thinkpad-t14-2.webp",
    "/products/lenovo-thinkpad-t14-3.webp"
  ],
  "lenovo-thinkpad-t460": [
    "/products/lenovo-thinkpad-t460.webp",
    "/products/lenovo-thinkpad-t460-2.webp",
    "/products/lenovo-thinkpad-t460-3.webp"
  ],
  "lenovo-thinkpad-x240": [
    "/products/lenovo-thinkpad-x240.webp",
    "/products/lenovo-thinkpad-x240-2.webp",
    "/products/lenovo-thinkpad-x240-3.webp"
  ],
  "logitech-c270-webcam": [
    "/products/logitech-c270-webcam.webp",
    "/products/logitech-c270-webcam-2.webp",
    "/products/logitech-c270-webcam-3.webp"
  ],
  "logitech-h111-headset": [
    "/products/logitech-h111-headset.webp",
    "/products/logitech-h111-headset-2.webp",
    "/products/logitech-h111-headset-3.webp"
  ],
  "logitech-k380-keyboard": [
    "/products/logitech-k380-keyboard.webp",
    "/products/logitech-k380-keyboard-2.webp",
    "/products/logitech-k380-keyboard-3.webp"
  ],
  "logitech-m170-mouse": [
    "/products/logitech-m170-mouse.webp",
    "/products/logitech-m170-mouse-2.webp",
    "/products/logitech-m170-mouse-3.webp"
  ],
  "logitech-mk270": [
    "/products/logitech-mk270.webp",
    "/products/logitech-mk270-2.webp",
    "/products/logitech-mk270-3.webp"
  ],
  "macbook-air-m1": [
    "/products/macbook-air-m1.webp",
    "/products/macbook-air-m1-2.webp",
    "/products/macbook-air-m1-3.webp"
  ],
  "macbook-air-m2": [
    "/products/macbook-air-m2.webp",
    "/products/macbook-air-m2-2.webp",
    "/products/macbook-air-m2-3.webp"
  ],
  "macbook-pro-13-m2": [
    "/products/macbook-pro-13-m2.webp",
    "/products/macbook-pro-13-m2-2.webp",
    "/products/macbook-pro-13-m2-3.webp"
  ],
  "macbook-pro-14-m3": [
    "/products/macbook-pro-14-m3.webp",
    "/products/macbook-pro-14-m3-2.webp",
    "/products/macbook-pro-14-m3-3.webp"
  ],
  "mercury-power-bank": [
    "/products/mercury-power-bank.webp",
    "/products/mercury-power-bank-2.webp",
    "/products/mercury-power-bank-3.webp"
  ],
  "mercury-ups-650va": [
    "/products/mercury-ups-650va.webp",
    "/products/mercury-ups-650va-2.webp",
    "/products/mercury-ups-650va-3.webp"
  ],
  "mercury-ups-850va": [
    "/products/mercury-ups-850va.webp",
    "/products/mercury-ups-850va-2.webp",
    "/products/mercury-ups-850va-3.webp"
  ],
  "microsd-64gb": [
    "/products/microsd-64gb.webp"
  ],
  "power-bank-10000": [
    "/products/power-bank-10000.webp"
  ],
  "power-bank-20000": [
    "/products/power-bank-20000.webp"
  ],
  "ram-ddr4-16gb-sodimm": [
    "/products/ram-ddr4-16gb-sodimm.webp"
  ],
  "ram-ddr4-8gb-dimm": [
    "/products/ram-ddr4-8gb-dimm.webp"
  ],
  "ram-ddr4-8gb-sodimm": [
    "/products/ram-ddr4-8gb-sodimm.webp"
  ],
  "sandisk-flash-128gb": [
    "/products/sandisk-flash-128gb.webp",
    "/products/sandisk-flash-128gb-2.webp",
    "/products/sandisk-flash-128gb-3.webp"
  ],
  "sandisk-flash-64gb": [
    "/products/sandisk-flash-64gb.webp"
  ],
  "sandisk-microsd-128gb": [
    "/products/sandisk-microsd-128gb.webp",
    "/products/sandisk-microsd-128gb-2.webp",
    "/products/sandisk-microsd-128gb-3.webp"
  ],
  "sandisk-ssd-1tb": [
    "/products/sandisk-ssd-1tb.webp",
    "/products/sandisk-ssd-1tb-2.webp",
    "/products/sandisk-ssd-1tb-3.webp"
  ],
  "sandisk-ssd-500gb": [
    "/products/sandisk-ssd-500gb.webp",
    "/products/sandisk-ssd-500gb-2.webp",
    "/products/sandisk-ssd-500gb-3.webp"
  ],
  "ssd-480gb-sata": [
    "/products/ssd-480gb-sata.webp"
  ],
  "ssd-nvme-500gb": [
    "/products/ssd-nvme-500gb.webp"
  ],
  "tp-link-archer-c20": [
    "/products/tp-link-archer-c20.webp",
    "/products/tp-link-archer-c20-2.webp",
    "/products/tp-link-archer-c20-3.webp"
  ],
  "tp-link-archer-c6": [
    "/products/tp-link-archer-c6.webp",
    "/products/tp-link-archer-c6-2.webp",
    "/products/tp-link-archer-c6-3.webp"
  ],
  "tp-link-re200-extender": [
    "/products/tp-link-re200-extender.webp",
    "/products/tp-link-re200-extender-2.webp",
    "/products/tp-link-re200-extender-3.webp"
  ],
  "tp-link-tl-sg108": [
    "/products/tp-link-tl-sg108.webp",
    "/products/tp-link-tl-sg108-2.webp",
    "/products/tp-link-tl-sg108-3.webp"
  ],
  "usb-c-charger-65w": [
    "/products/usb-c-charger-65w.webp"
  ],
  "wd-blue-ssd-500gb": [
    "/products/wd-blue-ssd-500gb.webp",
    "/products/wd-blue-ssd-500gb-2.webp",
    "/products/wd-blue-ssd-500gb-3.webp"
  ],
  "wd-elements-1tb-hdd": [
    "/products/wd-elements-1tb-hdd.webp",
    "/products/wd-elements-1tb-hdd-2.webp",
    "/products/wd-elements-1tb-hdd-3.webp"
  ],
  "wd-elements-2tb": [
    "/products/wd-elements-2tb.webp",
    "/products/wd-elements-2tb-2.webp",
    "/products/wd-elements-2tb-3.webp"
  ],
  "wd-passport-1tb": [
    "/products/wd-passport-1tb.webp",
    "/products/wd-passport-1tb-2.webp",
    "/products/wd-passport-1tb-3.webp"
  ]
};
