// Auto-generated by scripts/copy-videos.mjs — curated showcase videos.
export type VideoItem = { src: string; title: string };
export const videos: VideoItem[] = [
  {
    "src": "/videos/v-01.mp4",
    "title": "Laptop Showcase"
  },
  {
    "src": "/videos/v-02.mp4",
    "title": "In-Store Tour"
  },
  {
    "src": "/videos/v-03.mp4",
    "title": "Unboxing & First Look"
  },
  {
    "src": "/videos/v-04.mp4",
    "title": "Performance Demo"
  },
  {
    "src": "/videos/v-05.mp4",
    "title": "Customer Pickup"
  },
  {
    "src": "/videos/v-06.mp4",
    "title": "Gaming Laptop Reel"
  },
  {
    "src": "/videos/v-07.mp4",
    "title": "MacBook Spotlight"
  },
  {
    "src": "/videos/v-08.mp4",
    "title": "Business Series"
  },
  {
    "src": "/videos/v-09.mp4",
    "title": "Desktop Setup"
  },
  {
    "src": "/videos/v-10.mp4",
    "title": "Accessories Lineup"
  },
  {
    "src": "/videos/v-11.mp4",
    "title": "Deal of the Week"
  },
  {
    "src": "/videos/v-12.mp4",
    "title": "Quality Check"
  },
  {
    "src": "/videos/v-13.mp4",
    "title": "New Arrivals"
  },
  {
    "src": "/videos/v-14.mp4",
    "title": "Repairs & Support"
  },
  {
    "src": "/videos/v-15.mp4",
    "title": "Behind the Counter"
  },
  {
    "src": "/videos/v-16.mp4",
    "title": "Tech Tips"
  },
  {
    "src": "/videos/v-17.mp4",
    "title": "Featured Device"
  },
  {
    "src": "/videos/v-18.mp4",
    "title": "OnlineTech Daily"
  }
];
